# Generated by Django 5.2.3 on 2025-07-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
